// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shop/v1/shop.proto

package shopv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product — товар магазина (рассыпной чай, посуда, наборы) с реальным остатком.
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"` // puer | oolong | red | white | green | teaware | gift
	PriceCents    int64                  `protobuf:"varint,6,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	WeightGrams   int32                  `protobuf:"varint,8,opt,name=weight_grams,json=weightGrams,proto3" json:"weight_grams,omitempty"`
	Unit          string                 `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"` // «50 г», «357 г (блин)», «1 шт»
	ImageUrl      string                 `protobuf:"bytes,10,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	StockQty      int32                  `protobuf:"varint,11,opt,name=stock_qty,json=stockQty,proto3" json:"stock_qty,omitempty"` // реальный складской остаток
	Available     bool                   `protobuf:"varint,12,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetWeightGrams() int32 {
	if x != nil {
		return x.WeightGrams
	}
	return 0
}

func (x *Product) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetStockQty() int32 {
	if x != nil {
		return x.StockQty
	}
	return 0
}

func (x *Product) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // пусто — все
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CartItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku            string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,5,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	SubtotalCents  int64                  `protobuf:"varint,6,opt,name=subtotal_cents,json=subtotalCents,proto3" json:"subtotal_cents,omitempty"`
	StockQty       int32                  `protobuf:"varint,7,opt,name=stock_qty,json=stockQty,proto3" json:"stock_qty,omitempty"` // остаток для проверки доступности
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{4}
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CartItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *CartItem) GetSubtotalCents() int64 {
	if x != nil {
		return x.SubtotalCents
	}
	return 0
}

func (x *CartItem) GetStockQty() int32 {
	if x != nil {
		return x.StockQty
	}
	return 0
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalCents    int64                  `protobuf:"varint,3,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_shop_v1_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{5}
}

func (x *Cart) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

type CartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartRequest) Reset() {
	*x = CartRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartRequest) ProtoMessage() {}

func (x *CartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartRequest.ProtoReflect.Descriptor instead.
func (*CartRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{6}
}

func (x *CartRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{7}
}

func (x *AddToCartRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *AddToCartRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddToCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFromCartRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *RemoveFromCartRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RemoveFromCartRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type OrderItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,4,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	SubtotalCents  int64                  `protobuf:"varint,5,opt,name=subtotal_cents,json=subtotalCents,proto3" json:"subtotal_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_shop_v1_shop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{9}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *OrderItem) GetSubtotalCents() int64 {
	if x != nil {
		return x.SubtotalCents
	}
	return 0
}

type Order struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // created | paid | shipped | delivered | cancelled
	Customer           string                 `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	Phone              string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email              string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Country            string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Region             string                 `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`
	City               string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	Address            string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	PostalCode         string                 `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Comment            string                 `protobuf:"bytes,12,opt,name=comment,proto3" json:"comment,omitempty"`
	ItemsSubtotalCents int64                  `protobuf:"varint,13,opt,name=items_subtotal_cents,json=itemsSubtotalCents,proto3" json:"items_subtotal_cents,omitempty"`
	DeliveryCents      int64                  `protobuf:"varint,14,opt,name=delivery_cents,json=deliveryCents,proto3" json:"delivery_cents,omitempty"`
	TotalCents         int64                  `protobuf:"varint,15,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	TrackingCode       string                 `protobuf:"bytes,16,opt,name=tracking_code,json=trackingCode,proto3" json:"tracking_code,omitempty"`
	Items              []*OrderItem           `protobuf:"bytes,17,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_shop_v1_shop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{10}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *Order) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Order) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Order) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Order) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Order) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Order) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Order) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Order) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Order) GetItemsSubtotalCents() int64 {
	if x != nil {
		return x.ItemsSubtotalCents
	}
	return 0
}

func (x *Order) GetDeliveryCents() int64 {
	if x != nil {
		return x.DeliveryCents
	}
	return 0
}

func (x *Order) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Order) GetTrackingCode() string {
	if x != nil {
		return x.TrackingCode
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // пусто для гостя
	Customer      string                 `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Region        string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Comment       string                 `protobuf:"bytes,11,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{11}
}

func (x *CheckoutRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *CheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckoutRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *CheckoutRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CheckoutRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckoutRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CheckoutRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CheckoutRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CheckoutRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CheckoutRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CheckoutRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_shop_v1_shop_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{14}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ListAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllOrdersRequest) Reset() {
	*x = ListAllOrdersRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllOrdersRequest) ProtoMessage() {}

func (x *ListAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{15}
}

func (x *ListAllOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceCents    int64                  `protobuf:"varint,2,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	StockQty      int32                  `protobuf:"varint,3,opt,name=stock_qty,json=stockQty,proto3" json:"stock_qty,omitempty"`
	Available     bool                   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *UpdateProductRequest) GetStockQty() int32 {
	if x != nil {
		return x.StockQty
	}
	return 0
}

func (x *UpdateProductRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TrackingCode  string                 `protobuf:"bytes,3,opt,name=tracking_code,json=trackingCode,proto3" json:"tracking_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_shop_v1_shop_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_shop_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_shop_v1_shop_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateOrderStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetTrackingCode() string {
	if x != nil {
		return x.TrackingCode
	}
	return ""
}

var File_shop_v1_shop_proto protoreflect.FileDescriptor

const file_shop_v1_shop_proto_rawDesc = "" +
	"\n" +
	"\x12shop/v1/shop.proto\x12\ashop.v1\"\xc9\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1f\n" +
	"\vprice_cents\x18\x06 \x01(\x03R\n" +
	"priceCents\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12!\n" +
	"\fweight_grams\x18\b \x01(\x05R\vweightGrams\x12\x12\n" +
	"\x04unit\x18\t \x01(\tR\x04unit\x12\x1b\n" +
	"\timage_url\x18\n" +
	" \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tstock_qty\x18\v \x01(\x05R\bstockQty\x12\x1c\n" +
	"\tavailable\x18\f \x01(\bR\tavailable\"1\n" +
	"\x13ListProductsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"D\n" +
	"\x14ListProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.shop.v1.ProductR\bproducts\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd9\x01\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x05 \x01(\x03R\x0eunitPriceCents\x12%\n" +
	"\x0esubtotal_cents\x18\x06 \x01(\x03R\rsubtotalCents\x12\x1b\n" +
	"\tstock_qty\x18\a \x01(\x05R\bstockQty\"i\n" +
	"\x04Cart\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.shop.v1.CartItemR\x05items\x12\x1f\n" +
	"\vtotal_cents\x18\x03 \x01(\x03R\n" +
	"totalCents\"&\n" +
	"\vCartRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\"f\n" +
	"\x10AddToCartRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"k\n" +
	"\x15RemoveFromCartRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\xab\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x04 \x01(\x03R\x0eunitPriceCents\x12%\n" +
	"\x0esubtotal_cents\x18\x05 \x01(\x03R\rsubtotalCents\"\x93\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bcustomer\x18\x04 \x01(\tR\bcustomer\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\b \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x1f\n" +
	"\vpostal_code\x18\v \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acomment\x18\f \x01(\tR\acomment\x120\n" +
	"\x14items_subtotal_cents\x18\r \x01(\x03R\x12itemsSubtotalCents\x12%\n" +
	"\x0edelivery_cents\x18\x0e \x01(\x03R\rdeliveryCents\x12\x1f\n" +
	"\vtotal_cents\x18\x0f \x01(\x03R\n" +
	"totalCents\x12#\n" +
	"\rtracking_code\x18\x10 \x01(\tR\ftrackingCode\x12(\n" +
	"\x05items\x18\x11 \x03(\v2\x12.shop.v1.OrderItemR\x05items\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\tR\tcreatedAt\"\xa6\x02\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcustomer\x18\x03 \x01(\tR\bcustomer\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x1f\n" +
	"\vpostal_code\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acomment\x18\v \x01(\tR\acomment\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\x12ListOrdersResponse\x12&\n" +
	"\x06orders\x18\x01 \x03(\v2\x0e.shop.v1.OrderR\x06orders\",\n" +
	"\x14ListAllOrdersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x82\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprice_cents\x18\x02 \x01(\x03R\n" +
	"priceCents\x12\x1b\n" +
	"\tstock_qty\x18\x03 \x01(\x05R\bstockQty\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\bR\tavailable\"g\n" +
	"\x18UpdateOrderStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rtracking_code\x18\x03 \x01(\tR\ftrackingCode2\xfa\x05\n" +
	"\vShopService\x12K\n" +
	"\fListProducts\x12\x1c.shop.v1.ListProductsRequest\x1a\x1d.shop.v1.ListProductsResponse\x12:\n" +
	"\n" +
	"GetProduct\x12\x1a.shop.v1.GetProductRequest\x1a\x10.shop.v1.Product\x12.\n" +
	"\aGetCart\x12\x14.shop.v1.CartRequest\x1a\r.shop.v1.Cart\x125\n" +
	"\tAddToCart\x12\x19.shop.v1.AddToCartRequest\x1a\r.shop.v1.Cart\x12?\n" +
	"\x0eRemoveFromCart\x12\x1e.shop.v1.RemoveFromCartRequest\x1a\r.shop.v1.Cart\x120\n" +
	"\tClearCart\x12\x14.shop.v1.CartRequest\x1a\r.shop.v1.Cart\x124\n" +
	"\bCheckout\x12\x18.shop.v1.CheckoutRequest\x1a\x0e.shop.v1.Order\x124\n" +
	"\bGetOrder\x12\x18.shop.v1.GetOrderRequest\x1a\x0e.shop.v1.Order\x12E\n" +
	"\n" +
	"ListOrders\x12\x1a.shop.v1.ListOrdersRequest\x1a\x1b.shop.v1.ListOrdersResponse\x12@\n" +
	"\rUpdateProduct\x12\x1d.shop.v1.UpdateProductRequest\x1a\x10.shop.v1.Product\x12K\n" +
	"\rListAllOrders\x12\x1d.shop.v1.ListAllOrdersRequest\x1a\x1b.shop.v1.ListOrdersResponse\x12F\n" +
	"\x11UpdateOrderStatus\x12!.shop.v1.UpdateOrderStatusRequest\x1a\x0e.shop.v1.OrderB,Z*tea-platform/internal/genpb/shop/v1;shopv1b\x06proto3"

var (
	file_shop_v1_shop_proto_rawDescOnce sync.Once
	file_shop_v1_shop_proto_rawDescData []byte
)

func file_shop_v1_shop_proto_rawDescGZIP() []byte {
	file_shop_v1_shop_proto_rawDescOnce.Do(func() {
		file_shop_v1_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)))
	})
	return file_shop_v1_shop_proto_rawDescData
}

var file_shop_v1_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_shop_v1_shop_proto_goTypes = []any{
	(*Product)(nil),                  // 0: shop.v1.Product
	(*ListProductsRequest)(nil),      // 1: shop.v1.ListProductsRequest
	(*ListProductsResponse)(nil),     // 2: shop.v1.ListProductsResponse
	(*GetProductRequest)(nil),        // 3: shop.v1.GetProductRequest
	(*CartItem)(nil),                 // 4: shop.v1.CartItem
	(*Cart)(nil),                     // 5: shop.v1.Cart
	(*CartRequest)(nil),              // 6: shop.v1.CartRequest
	(*AddToCartRequest)(nil),         // 7: shop.v1.AddToCartRequest
	(*RemoveFromCartRequest)(nil),    // 8: shop.v1.RemoveFromCartRequest
	(*OrderItem)(nil),                // 9: shop.v1.OrderItem
	(*Order)(nil),                    // 10: shop.v1.Order
	(*CheckoutRequest)(nil),          // 11: shop.v1.CheckoutRequest
	(*GetOrderRequest)(nil),          // 12: shop.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),        // 13: shop.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),       // 14: shop.v1.ListOrdersResponse
	(*ListAllOrdersRequest)(nil),     // 15: shop.v1.ListAllOrdersRequest
	(*UpdateProductRequest)(nil),     // 16: shop.v1.UpdateProductRequest
	(*UpdateOrderStatusRequest)(nil), // 17: shop.v1.UpdateOrderStatusRequest
}
var file_shop_v1_shop_proto_depIdxs = []int32{
	0,  // 0: shop.v1.ListProductsResponse.products:type_name -> shop.v1.Product
	4,  // 1: shop.v1.Cart.items:type_name -> shop.v1.CartItem
	9,  // 2: shop.v1.Order.items:type_name -> shop.v1.OrderItem
	10, // 3: shop.v1.ListOrdersResponse.orders:type_name -> shop.v1.Order
	1,  // 4: shop.v1.ShopService.ListProducts:input_type -> shop.v1.ListProductsRequest
	3,  // 5: shop.v1.ShopService.GetProduct:input_type -> shop.v1.GetProductRequest
	6,  // 6: shop.v1.ShopService.GetCart:input_type -> shop.v1.CartRequest
	7,  // 7: shop.v1.ShopService.AddToCart:input_type -> shop.v1.AddToCartRequest
	8,  // 8: shop.v1.ShopService.RemoveFromCart:input_type -> shop.v1.RemoveFromCartRequest
	6,  // 9: shop.v1.ShopService.ClearCart:input_type -> shop.v1.CartRequest
	11, // 10: shop.v1.ShopService.Checkout:input_type -> shop.v1.CheckoutRequest
	12, // 11: shop.v1.ShopService.GetOrder:input_type -> shop.v1.GetOrderRequest
	13, // 12: shop.v1.ShopService.ListOrders:input_type -> shop.v1.ListOrdersRequest
	16, // 13: shop.v1.ShopService.UpdateProduct:input_type -> shop.v1.UpdateProductRequest
	15, // 14: shop.v1.ShopService.ListAllOrders:input_type -> shop.v1.ListAllOrdersRequest
	17, // 15: shop.v1.ShopService.UpdateOrderStatus:input_type -> shop.v1.UpdateOrderStatusRequest
	2,  // 16: shop.v1.ShopService.ListProducts:output_type -> shop.v1.ListProductsResponse
	0,  // 17: shop.v1.ShopService.GetProduct:output_type -> shop.v1.Product
	5,  // 18: shop.v1.ShopService.GetCart:output_type -> shop.v1.Cart
	5,  // 19: shop.v1.ShopService.AddToCart:output_type -> shop.v1.Cart
	5,  // 20: shop.v1.ShopService.RemoveFromCart:output_type -> shop.v1.Cart
	5,  // 21: shop.v1.ShopService.ClearCart:output_type -> shop.v1.Cart
	10, // 22: shop.v1.ShopService.Checkout:output_type -> shop.v1.Order
	10, // 23: shop.v1.ShopService.GetOrder:output_type -> shop.v1.Order
	14, // 24: shop.v1.ShopService.ListOrders:output_type -> shop.v1.ListOrdersResponse
	0,  // 25: shop.v1.ShopService.UpdateProduct:output_type -> shop.v1.Product
	14, // 26: shop.v1.ShopService.ListAllOrders:output_type -> shop.v1.ListOrdersResponse
	10, // 27: shop.v1.ShopService.UpdateOrderStatus:output_type -> shop.v1.Order
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_shop_v1_shop_proto_init() }
func file_shop_v1_shop_proto_init() {
	if File_shop_v1_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_v1_shop_proto_rawDesc), len(file_shop_v1_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_v1_shop_proto_goTypes,
		DependencyIndexes: file_shop_v1_shop_proto_depIdxs,
		MessageInfos:      file_shop_v1_shop_proto_msgTypes,
	}.Build()
	File_shop_v1_shop_proto = out.File
	file_shop_v1_shop_proto_goTypes = nil
	file_shop_v1_shop_proto_depIdxs = nil
}
