// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: delivery/v1/delivery.proto

package deliveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_CREATED     DeliveryStatus = 1 // создана, ждёт отправки
	DeliveryStatus_DELIVERY_STATUS_DISPATCHED  DeliveryStatus = 2 // отправлена/курьер назначен
	DeliveryStatus_DELIVERY_STATUS_DELIVERED   DeliveryStatus = 3 // доставлена
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_CREATED",
		2: "DELIVERY_STATUS_DISPATCHED",
		3: "DELIVERY_STATUS_DELIVERED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_CREATED":     1,
		"DELIVERY_STATUS_DISPATCHED":  2,
		"DELIVERY_STATUS_DELIVERED":   3,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_delivery_v1_delivery_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_delivery_v1_delivery_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{0}
}

type Delivery struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FulfillmentType string                 `protobuf:"bytes,2,opt,name=fulfillment_type,json=fulfillmentType,proto3" json:"fulfillment_type,omitempty"` // shop_delivery | food_courier | dine_in
	Status          DeliveryStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=delivery.v1.DeliveryStatus" json:"status,omitempty"`
	TrackingCode    string                 `protobuf:"bytes,4,opt,name=tracking_code,json=trackingCode,proto3" json:"tracking_code,omitempty"` // для доставки чая (магазин)
	Courier         string                 `protobuf:"bytes,5,opt,name=courier,proto3" json:"courier,omitempty"`                               // для доставки еды курьером
	Eta             string                 `protobuf:"bytes,6,opt,name=eta,proto3" json:"eta,omitempty"`                                       // ориентир времени доставки
	CreatedAt       string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // RFC3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{0}
}

func (x *Delivery) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Delivery) GetFulfillmentType() string {
	if x != nil {
		return x.FulfillmentType
	}
	return ""
}

func (x *Delivery) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *Delivery) GetTrackingCode() string {
	if x != nil {
		return x.TrackingCode
	}
	return ""
}

func (x *Delivery) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *Delivery) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *Delivery) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryRequest) Reset() {
	*x = GetDeliveryRequest{}
	mi := &file_delivery_v1_delivery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryRequest) ProtoMessage() {}

func (x *GetDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_v1_delivery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_delivery_v1_delivery_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeliveryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_delivery_v1_delivery_proto protoreflect.FileDescriptor

const file_delivery_v1_delivery_proto_rawDesc = "" +
	"\n" +
	"\x1adelivery/v1/delivery.proto\x12\vdelivery.v1\"\xf5\x01\n" +
	"\bDelivery\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12)\n" +
	"\x10fulfillment_type\x18\x02 \x01(\tR\x0ffulfillmentType\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.delivery.v1.DeliveryStatusR\x06status\x12#\n" +
	"\rtracking_code\x18\x04 \x01(\tR\ftrackingCode\x12\x18\n" +
	"\acourier\x18\x05 \x01(\tR\acourier\x12\x10\n" +
	"\x03eta\x18\x06 \x01(\tR\x03eta\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"/\n" +
	"\x12GetDeliveryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId*\x8d\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_STATUS_CREATED\x10\x01\x12\x1e\n" +
	"\x1aDELIVERY_STATUS_DISPATCHED\x10\x02\x12\x1d\n" +
	"\x19DELIVERY_STATUS_DELIVERED\x10\x032X\n" +
	"\x0fDeliveryService\x12E\n" +
	"\vGetDelivery\x12\x1f.delivery.v1.GetDeliveryRequest\x1a\x15.delivery.v1.DeliveryB4Z2tea-platform/internal/genpb/delivery/v1;deliveryv1b\x06proto3"

var (
	file_delivery_v1_delivery_proto_rawDescOnce sync.Once
	file_delivery_v1_delivery_proto_rawDescData []byte
)

func file_delivery_v1_delivery_proto_rawDescGZIP() []byte {
	file_delivery_v1_delivery_proto_rawDescOnce.Do(func() {
		file_delivery_v1_delivery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_v1_delivery_proto_rawDesc), len(file_delivery_v1_delivery_proto_rawDesc)))
	})
	return file_delivery_v1_delivery_proto_rawDescData
}

var file_delivery_v1_delivery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_delivery_v1_delivery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_delivery_v1_delivery_proto_goTypes = []any{
	(DeliveryStatus)(0),        // 0: delivery.v1.DeliveryStatus
	(*Delivery)(nil),           // 1: delivery.v1.Delivery
	(*GetDeliveryRequest)(nil), // 2: delivery.v1.GetDeliveryRequest
}
var file_delivery_v1_delivery_proto_depIdxs = []int32{
	0, // 0: delivery.v1.Delivery.status:type_name -> delivery.v1.DeliveryStatus
	2, // 1: delivery.v1.DeliveryService.GetDelivery:input_type -> delivery.v1.GetDeliveryRequest
	1, // 2: delivery.v1.DeliveryService.GetDelivery:output_type -> delivery.v1.Delivery
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_delivery_v1_delivery_proto_init() }
func file_delivery_v1_delivery_proto_init() {
	if File_delivery_v1_delivery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_v1_delivery_proto_rawDesc), len(file_delivery_v1_delivery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_v1_delivery_proto_goTypes,
		DependencyIndexes: file_delivery_v1_delivery_proto_depIdxs,
		EnumInfos:         file_delivery_v1_delivery_proto_enumTypes,
		MessageInfos:      file_delivery_v1_delivery_proto_msgTypes,
	}.Build()
	File_delivery_v1_delivery_proto = out.File
	file_delivery_v1_delivery_proto_goTypes = nil
	file_delivery_v1_delivery_proto_depIdxs = nil
}
