// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProductKind различает домены платформы.
type ProductKind int32

const (
	ProductKind_PRODUCT_KIND_UNSPECIFIED ProductKind = 0
	ProductKind_PRODUCT_KIND_TEA_GOODS   ProductKind = 1 // товар магазина (чай, посуда)
	ProductKind_PRODUCT_KIND_DISH        ProductKind = 2 // блюдо ресторана
)

// Enum value maps for ProductKind.
var (
	ProductKind_name = map[int32]string{
		0: "PRODUCT_KIND_UNSPECIFIED",
		1: "PRODUCT_KIND_TEA_GOODS",
		2: "PRODUCT_KIND_DISH",
	}
	ProductKind_value = map[string]int32{
		"PRODUCT_KIND_UNSPECIFIED": 0,
		"PRODUCT_KIND_TEA_GOODS":   1,
		"PRODUCT_KIND_DISH":        2,
	}
)

func (x ProductKind) Enum() *ProductKind {
	p := new(ProductKind)
	*p = x
	return p
}

func (x ProductKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductKind) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_v1_catalog_proto_enumTypes[0].Descriptor()
}

func (ProductKind) Type() protoreflect.EnumType {
	return &file_catalog_v1_catalog_proto_enumTypes[0]
}

func (x ProductKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductKind.Descriptor instead.
func (ProductKind) EnumDescriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

// Product — единая модель позиции каталога.
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          ProductKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=catalog.v1.ProductKind" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`                        // напр. "shu_puer", "dim_sum", "dessert"
	PriceCents    int64                  `protobuf:"varint,6,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"` // цена в копейках
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`                        // ISO 4217, напр. "RUB"
	Available     bool                   `protobuf:"varint,8,opt,name=available,proto3" json:"available,omitempty"`                     // для блюд — отсутствие в стоп-листе
	ImageUrl      string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Sku           string                 `protobuf:"bytes,10,opt,name=sku,proto3" json:"sku,omitempty"`   // стабильный id из дизайна (frontend data-add)
	Unit          string                 `protobuf:"bytes,11,opt,name=unit,proto3" json:"unit,omitempty"` // объём/порция (напр. «900 мл», «0,3 л»)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetKind() ProductKind {
	if x != nil {
		return x.Kind
	}
	return ProductKind_PRODUCT_KIND_UNSPECIFIED
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type ListProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Опциональный фильтр по типу позиции. UNSPECIFIED — все.
	Kind ProductKind `protobuf:"varint,1,opt,name=kind,proto3,enum=catalog.v1.ProductKind" json:"kind,omitempty"`
	// Опциональный фильтр по категории. Пустая строка — все.
	Category      string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsRequest) GetKind() ProductKind {
	if x != nil {
		return x.Kind
	}
	return ProductKind_PRODUCT_KIND_UNSPECIFIED
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PriceCents    int64                  `protobuf:"varint,2,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *UpdateProductRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"\xb6\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x17.catalog.v1.ProductKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1f\n" +
	"\vprice_cents\x18\x06 \x01(\x03R\n" +
	"priceCents\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x1c\n" +
	"\tavailable\x18\b \x01(\bR\tavailable\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x10\n" +
	"\x03sku\x18\n" +
	" \x01(\tR\x03sku\x12\x12\n" +
	"\x04unit\x18\v \x01(\tR\x04unit\"^\n" +
	"\x13ListProductsRequest\x12+\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x17.catalog.v1.ProductKindR\x04kind\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"G\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.catalog.v1.ProductR\bproducts\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.catalog.v1.ProductR\aproduct\"e\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprice_cents\x18\x02 \x01(\x03R\n" +
	"priceCents\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable*^\n" +
	"\vProductKind\x12\x1c\n" +
	"\x18PRODUCT_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PRODUCT_KIND_TEA_GOODS\x10\x01\x12\x15\n" +
	"\x11PRODUCT_KIND_DISH\x10\x022\xf8\x01\n" +
	"\x0eCatalogService\x12Q\n" +
	"\fListProducts\x12\x1f.catalog.v1.ListProductsRequest\x1a .catalog.v1.ListProductsResponse\x12K\n" +
	"\n" +
	"GetProduct\x12\x1d.catalog.v1.GetProductRequest\x1a\x1e.catalog.v1.GetProductResponse\x12F\n" +
	"\rUpdateProduct\x12 .catalog.v1.UpdateProductRequest\x1a\x13.catalog.v1.ProductB2Z0tea-platform/internal/genpb/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(ProductKind)(0),             // 0: catalog.v1.ProductKind
	(*Product)(nil),              // 1: catalog.v1.Product
	(*ListProductsRequest)(nil),  // 2: catalog.v1.ListProductsRequest
	(*ListProductsResponse)(nil), // 3: catalog.v1.ListProductsResponse
	(*GetProductRequest)(nil),    // 4: catalog.v1.GetProductRequest
	(*GetProductResponse)(nil),   // 5: catalog.v1.GetProductResponse
	(*UpdateProductRequest)(nil), // 6: catalog.v1.UpdateProductRequest
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.v1.Product.kind:type_name -> catalog.v1.ProductKind
	0, // 1: catalog.v1.ListProductsRequest.kind:type_name -> catalog.v1.ProductKind
	1, // 2: catalog.v1.ListProductsResponse.products:type_name -> catalog.v1.Product
	1, // 3: catalog.v1.GetProductResponse.product:type_name -> catalog.v1.Product
	2, // 4: catalog.v1.CatalogService.ListProducts:input_type -> catalog.v1.ListProductsRequest
	4, // 5: catalog.v1.CatalogService.GetProduct:input_type -> catalog.v1.GetProductRequest
	6, // 6: catalog.v1.CatalogService.UpdateProduct:input_type -> catalog.v1.UpdateProductRequest
	3, // 7: catalog.v1.CatalogService.ListProducts:output_type -> catalog.v1.ListProductsResponse
	5, // 8: catalog.v1.CatalogService.GetProduct:output_type -> catalog.v1.GetProductResponse
	1, // 9: catalog.v1.CatalogService.UpdateProduct:output_type -> catalog.v1.Product
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		EnumInfos:         file_catalog_v1_catalog_proto_enumTypes,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
