// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order/v1/order.proto

package orderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FulfillmentType — способ получения заказа.
type FulfillmentType int32

const (
	FulfillmentType_FULFILLMENT_TYPE_UNSPECIFIED   FulfillmentType = 0
	FulfillmentType_FULFILLMENT_TYPE_SHOP_DELIVERY FulfillmentType = 1 // доставка чая (магазин)
	FulfillmentType_FULFILLMENT_TYPE_FOOD_COURIER  FulfillmentType = 2 // доставка еды курьером
	FulfillmentType_FULFILLMENT_TYPE_DINE_IN       FulfillmentType = 3 // в ресторане (привязка к брони)
)

// Enum value maps for FulfillmentType.
var (
	FulfillmentType_name = map[int32]string{
		0: "FULFILLMENT_TYPE_UNSPECIFIED",
		1: "FULFILLMENT_TYPE_SHOP_DELIVERY",
		2: "FULFILLMENT_TYPE_FOOD_COURIER",
		3: "FULFILLMENT_TYPE_DINE_IN",
	}
	FulfillmentType_value = map[string]int32{
		"FULFILLMENT_TYPE_UNSPECIFIED":   0,
		"FULFILLMENT_TYPE_SHOP_DELIVERY": 1,
		"FULFILLMENT_TYPE_FOOD_COURIER":  2,
		"FULFILLMENT_TYPE_DINE_IN":       3,
	}
)

func (x FulfillmentType) Enum() *FulfillmentType {
	p := new(FulfillmentType)
	*p = x
	return p
}

func (x FulfillmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FulfillmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[0].Descriptor()
}

func (FulfillmentType) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[0]
}

func (x FulfillmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FulfillmentType.Descriptor instead.
func (FulfillmentType) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

// OrderStatus — состояние заказа в state machine.
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED     OrderStatus = 0
	OrderStatus_ORDER_STATUS_CREATED         OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAYMENT_PENDING OrderStatus = 2
	OrderStatus_ORDER_STATUS_PAID            OrderStatus = 3
	OrderStatus_ORDER_STATUS_CONFIRMED       OrderStatus = 4
	OrderStatus_ORDER_STATUS_COMPLETED       OrderStatus = 5
	OrderStatus_ORDER_STATUS_CANCELLED       OrderStatus = 6
	OrderStatus_ORDER_STATUS_PAYMENT_FAILED  OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_CREATED",
		2: "ORDER_STATUS_PAYMENT_PENDING",
		3: "ORDER_STATUS_PAID",
		4: "ORDER_STATUS_CONFIRMED",
		5: "ORDER_STATUS_COMPLETED",
		6: "ORDER_STATUS_CANCELLED",
		7: "ORDER_STATUS_PAYMENT_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":     0,
		"ORDER_STATUS_CREATED":         1,
		"ORDER_STATUS_PAYMENT_PENDING": 2,
		"ORDER_STATUS_PAID":            3,
		"ORDER_STATUS_CONFIRMED":       4,
		"ORDER_STATUS_COMPLETED":       5,
		"ORDER_STATUS_CANCELLED":       6,
		"ORDER_STATUS_PAYMENT_FAILED":  7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[1].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[1]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

type OrderItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,4,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	SubtotalCents  int64                  `protobuf:"varint,5,opt,name=subtotal_cents,json=subtotalCents,proto3" json:"subtotal_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *OrderItem) GetSubtotalCents() int64 {
	if x != nil {
		return x.SubtotalCents
	}
	return 0
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CartId          string                 `protobuf:"bytes,3,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	FulfillmentType FulfillmentType        `protobuf:"varint,4,opt,name=fulfillment_type,json=fulfillmentType,proto3,enum=order.v1.FulfillmentType" json:"fulfillment_type,omitempty"`
	Status          OrderStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	TotalCents      int64                  `protobuf:"varint,7,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Currency        string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Address         string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *Order) GetFulfillmentType() FulfillmentType {
	if x != nil {
		return x.FulfillmentType
	}
	return FulfillmentType_FULFILLMENT_TYPE_UNSPECIFIED
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CartId          string                 `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FulfillmentType FulfillmentType        `protobuf:"varint,3,opt,name=fulfillment_type,json=fulfillmentType,proto3,enum=order.v1.FulfillmentType" json:"fulfillment_type,omitempty"`
	Address         string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetFulfillmentType() FulfillmentType {
	if x != nil {
		return x.FulfillmentType
	}
	return FulfillmentType_FULFILLMENT_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\"\xab\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x04 \x01(\x03R\x0eunitPriceCents\x12%\n" +
	"\x0esubtotal_cents\x18\x05 \x01(\x03R\rsubtotalCents\"\xdf\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\acart_id\x18\x03 \x01(\tR\x06cartId\x12D\n" +
	"\x10fulfillment_type\x18\x04 \x01(\x0e2\x19.order.v1.FulfillmentTypeR\x0ffulfillmentType\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.order.v1.OrderStatusR\x06status\x12)\n" +
	"\x05items\x18\x06 \x03(\v2\x13.order.v1.OrderItemR\x05items\x12\x1f\n" +
	"\vtotal_cents\x18\a \x01(\x03R\n" +
	"totalCents\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xa6\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\tR\x06cartId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12D\n" +
	"\x10fulfillment_type\x18\x03 \x01(\x0e2\x19.order.v1.FulfillmentTypeR\x0ffulfillmentType\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*\x98\x01\n" +
	"\x0fFulfillmentType\x12 \n" +
	"\x1cFULFILLMENT_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eFULFILLMENT_TYPE_SHOP_DELIVERY\x10\x01\x12!\n" +
	"\x1dFULFILLMENT_TYPE_FOOD_COURIER\x10\x02\x12\x1c\n" +
	"\x18FULFILLMENT_TYPE_DINE_IN\x10\x03*\xf3\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_CREATED\x10\x01\x12 \n" +
	"\x1cORDER_STATUS_PAYMENT_PENDING\x10\x02\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_CONFIRMED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x06\x12\x1f\n" +
	"\x1bORDER_STATUS_PAYMENT_FAILED\x10\a2\x84\x01\n" +
	"\fOrderService\x12<\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x0f.order.v1.Order\x126\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x0f.order.v1.OrderB.Z,tea-platform/internal/genpb/order/v1;orderv1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_order_v1_order_proto_goTypes = []any{
	(FulfillmentType)(0),       // 0: order.v1.FulfillmentType
	(OrderStatus)(0),           // 1: order.v1.OrderStatus
	(*OrderItem)(nil),          // 2: order.v1.OrderItem
	(*Order)(nil),              // 3: order.v1.Order
	(*CreateOrderRequest)(nil), // 4: order.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),    // 5: order.v1.GetOrderRequest
}
var file_order_v1_order_proto_depIdxs = []int32{
	0, // 0: order.v1.Order.fulfillment_type:type_name -> order.v1.FulfillmentType
	1, // 1: order.v1.Order.status:type_name -> order.v1.OrderStatus
	2, // 2: order.v1.Order.items:type_name -> order.v1.OrderItem
	0, // 3: order.v1.CreateOrderRequest.fulfillment_type:type_name -> order.v1.FulfillmentType
	4, // 4: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	5, // 5: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	3, // 6: order.v1.OrderService.CreateOrder:output_type -> order.v1.Order
	3, // 7: order.v1.OrderService.GetOrder:output_type -> order.v1.Order
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		EnumInfos:         file_order_v1_order_proto_enumTypes,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
